[package]
name = "display"
version = "0.1.0"
edition = "2021"

[lib]
path = "display.rs"

[dependencies]
slide = { path = "../slide" }
sil = { path = "../sil" }

egui = { version = "0.21.0", default-features = false, features = [] }

